### ISSUE TITLE
pip install disqus doesn't work on Windows

### ISSUE THREAD

**Issue by monroews** [AguaClara/Textbook#29]
(base) C:\Users\mw24>pip install git+https://github.com/rmk135/sphinxcontrib-disqus
Collecting git+https://github.com/rmk135/sphinxcontrib-disqus
  Cloning https://github.com/rmk135/sphinxcontrib-disqus to c:\users\mw24\appdata\local\temp\pip-req-build-ggqja6w4
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
      File "c:\users\mw24\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\__init__.py", line 10, in <module>
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
      File "c:\users\mw24\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\extern\__init__.py", line 1, in <module>
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
      File "c:\users\mw24\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2985, in <module>
      File "c:\users\mw24\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2971, in _call_aside
      File "c:\users\mw24\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 3013, in _initialize_master_working_set
      File "c:\users\mw24\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2544, in activate
      File "c:\users\mw24\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2118, in declare_namespace
      File "c:\users\mw24\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2058, in _handle_ns
      File "c:\users\mw24\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2087, in _rebuild_mod_path
    AttributeError: '_NamespacePath' object has no attribute 'sort'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\mw24\AppData\Local\Temp\pip-req-build-ggqja6w4\

**Comment by ethan92429** [comment]
@juanchon998 weren't you able to get this working on your windows? The error Monroe has I think has to do with a namespace collision. I'm guessing this has something to do with having tried pip install sphinxcontrib-disqus. @monroews can you confirm that the other version of sphinxcontrib-disqus is fully uninstalled?

**Comment by juanchon998** [comment]
I was able to get this working on my computer. I included dealing with disqus in the contributor's guide, but that hasn't been publicly released at the time of this comment. Basically, run `pip uninstall sphinxcontrib-disqus` before pip installing this guy `pip install git+https://github.com/rmk135/sphinxcontrib-disqus`.

**Comment by monroews** [comment]
(base) C:\Users\mw24>pip uninstall sphinxcontrib-disqus
Skipping sphinxcontrib-disqus as it is not installed.

(base) C:\Users\mw24>pip install git+https://github.com/rmk135/sphinxcontrib-disqus
Collecting git+https://github.com/rmk135/sphinxcontrib-disqus
  Cloning https://github.com/rmk135/sphinxcontrib-disqus to c:\users\mw24\appdata\local\temp\pip-req-build-xicfypai
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
      File "c:\users\mw24\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\__init__.py", line 10, in <module>
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
      File "c:\users\mw24\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\setuptools\extern\__init__.py", line 1, in <module>
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
      File "c:\users\mw24\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2985, in <module>
      File "c:\users\mw24\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2971, in _call_aside
      File "c:\users\mw24\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 3013, in _initialize_master_working_set
      File "c:\users\mw24\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2544, in activate
      File "c:\users\mw24\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2118, in declare_namespace
      File "c:\users\mw24\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2058, in _handle_ns
      File "c:\users\mw24\anaconda3\lib\site-packages\setuptools-27.2.0-py3.6.egg\pkg_resources\__init__.py", line 2087, in _rebuild_mod_path
    AttributeError: '_NamespacePath' object has no attribute 'sort'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\mw24\AppData\Local\Temp\pip-req-build-xicfypai\

**Comment by monroews** [comment]
(base) C:\Users\mw24>pip list
Package                            Version
---------------------------------- -----------
aguaclara-research                 1.0.3
aide-design                        0.0.12
alabaster                          0.7.10
anaconda-client                    1.6.3
anaconda-navigator                 1.6.2
anaconda-project                   0.6.0
asn1crypto                         0.22.0
astroid                            1.4.9
astropy                            1.3.2
atomicwrites                       1.1.5
attrs                              18.1.0
Babel                              2.4.0
backports.shutil-get-terminal-size 1.0.0
beautifulsoup4                     4.6.0
bitarray                           0.8.1
blaze                              0.10.1
bleach                             1.5.0
bokeh                              0.12.5
boto                               2.46.1
Bottleneck                         1.2.1
cffi                               1.10.0
chardet                            3.0.3
click                              6.7
cloudpickle                        0.2.2
clyent                             1.2.2
colorama                           0.3.9
comtypes                           1.1.2
conda                              4.5.4
contextlib2                        0.5.5
cryptography                       1.8.1
cycler                             0.10.0
Cython                             0.25.2
cytoolz                            0.8.2
dask                               0.14.3
datashape                          0.5.4
decorator                          4.0.11
distributed                        1.16.3
docutils                           0.13.1
entrypoints                        0.2.2
et-xmlfile                         1.0.1
fastcache                          1.0.2
Flask                              0.12.2
Flask-Cors                         3.0.2
gevent                             1.2.1
greenlet                           0.4.12
h5py                               2.7.0
HeapDict                           1.0.0
html5lib                           0.999
idna                               2.5
imagesize                          0.7.1
ipykernel                          4.6.1
ipython                            5.3.0
ipython-genutils                   0.2.0
ipywidgets                         6.0.0
isort                              4.2.5
itsdangerous                       0.24
jdcal                              1.3
jedi                               0.10.2
Jinja2                             2.9.6
jsonschema                         2.6.0
jupyter                            1.0.0
jupyter-client                     5.0.1
jupyter-console                    5.1.0
jupyter-core                       4.3.0
lazy-object-proxy                  1.2.2
llvmlite                           0.18.0
locket                             0.2.0
lxml                               3.7.3
MarkupSafe                         0.23
matplotlib                         2.0.2
menuinst                           1.4.7
mistune                            0.7.4
more-itertools                     4.2.0
mpmath                             0.19
msgpack-python                     0.4.8
multipledispatch                   0.4.9
navigator-updater                  0.1.0
nbconvert                          5.1.1
nbformat                           4.3.0
networkx                           1.11
nltk                               3.2.3
nose                               1.3.7
notebook                           5.0.0
numba                              0.33.0
numexpr                            2.6.2
numpy                              1.12.1
numpydoc                           0.6.0
odo                                0.5.0
olefile                            0.44
openpyxl                           2.4.7
packaging                          16.8
pandas                             0.20.1
pandoc                             1.0.2
pandocfilters                      1.4.1
partd                              0.3.8
path.py                            10.3.1
pathlib2                           2.2.1
patsy                              0.4.1
pep8                               1.7.0
pickleshare                        0.7.4
Pillow                             4.1.1
Pint                               0.8.1
pip                                10.0.1
plotly                             2.6.0
pluggy                             0.6.0
ply                                3.10
prompt-toolkit                     1.0.14
psutil                             5.2.2
py                                 1.5.3
pycodestyle                        2.4.0
pycosat                            0.6.3
pycparser                          2.17
pycrypto                           2.6.1
pycurl                             7.43.0
pyEDFlib                           0.1.11
pyflakes                           1.5.0
Pygments                           2.2.0
pylint                             1.6.4
pyodbc                             4.0.16
pyOpenSSL                          17.0.0
pyparsing                          2.1.4
pytest                             3.6.2
pytexit                            0.1.8
python-dateutil                    2.6.0
pytz                               2017.2
PyWavelets                         0.5.2
pywin32                            220
PyYAML                             3.12
pyzmq                              16.0.2
QtAwesome                          0.4.4
qtconsole                          4.3.0
QtPy                               1.2.1
requests                           2.14.2
rope-py3k                          0.9.4.post1
scikit-image                       0.13.0
scikit-learn                       0.18.1
scipy                              0.19.0
seaborn                            0.7.1
setuptools                         27.2.0
simplegeneric                      0.8.1
singledispatch                     3.4.0.3
six                                1.10.0
snowballstemmer                    1.2.1
sortedcollections                  0.5.3
sortedcontainers                   1.5.7
Sphinx                             1.7.5
sphinx-rtd-theme                   0.4.0
sphinxcontrib-websupport           1.1.0
spyder                             3.1.4
SQLAlchemy                         1.1.9
statsmodels                        0.8.0
sympy                              1.0
tables                             3.2.2
tblib                              1.3.2
testpath                           0.3
toolz                              0.8.2
tornado                            4.5.1
traitlets                          4.3.2
unicodecsv                         0.14.1
wcwidth                            0.1.7
Werkzeug                           0.12.2
wheel                              0.29.0
widgetsnbextension                 2.0.0
win-unicode-console                0.5
wrapt                              1.10.10
xlrd                               1.0.0
XlsxWriter                         0.9.6
xlwings                            0.10.4
xlwt                               1.2.0
zict                               0.1.2

(base) C:\Users\mw24>pip show aide_design
Name: aide-design
Version: 0.0.12
Summary: AguaClara Infrastructure Design Engine
Home-page: https://github.com/AguaClara/aguaclara_design
Author: AguaClara at Cornell
Author-email: aguaclara@cornell.edu
License: MIT
Location: c:\users\mw24\anaconda3\lib\site-packages
Requires: pint, pandas, numpy, scipy, matplotlib
Required-by: aguaclara-research

pip 10.0.1 from c:\users\mw24\anaconda3\lib\site-packages\pip (python 3.6)

**Comment by ethan92429** [comment]
I don't know what is happening. I can investigate when I come up there. Is this preventing you from building? If so, I could make a branch that has disqus functionality removed that you could work on. Let me know if that's something you need!

**Comment by monroews** [comment]
I have removed disqus from my branch and thus I can do builds on my computer without a problem. So this isn't urgent.

**Comment by juanchon998** [comment]
This is a test reply to show John Finn how email interacts with GitHub

Juan Guzmán

*EIT, Master of Engineering*
AguaClara Engineer

[image: https://www.aguaclarareach.org/] <https://www.aguaclarareach.org/>


On Sun, Aug 5, 2018 at 6:15 AM, Monroe Weber-Shirk <notifications@github.com
